"""initial_schema

Revision ID: b44a5f565370
Revises:
Create Date: 2026-07-23 10:23:16.558063
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "b44a5f565370"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("slot_minutes", sa.Integer(), nullable=False),
        sa.Column("admin_api_key_hash", sa.String(length=512), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)
    op.create_table(
        "booking_services",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_booking_service_name"),
    )
    op.create_index(
        op.f("ix_booking_services_tenant_id"), "booking_services", ["tenant_id"], unique=False
    )
    op.create_table(
        "business_hours",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("open_time", sa.Time(), nullable=False),
        sa.Column("close_time", sa.Time(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "weekday", name="uq_business_hour_day"),
    )
    op.create_index(
        op.f("ix_business_hours_tenant_id"), "business_hours", ["tenant_id"], unique=False
    )
    op.create_table(
        "conversation_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("line_user_id", sa.String(length=64), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("message_type", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_messages_line_user_id"),
        "conversation_messages",
        ["line_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_messages_tenant_id"),
        "conversation_messages",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "datasets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", "version", name="uq_dataset_version"),
    )
    op.create_index(op.f("ix_datasets_status"), "datasets", ["status"], unique=False)
    op.create_index(op.f("ix_datasets_tenant_id"), "datasets", ["tenant_id"], unique=False)
    op.create_index(
        "uq_dataset_active_per_tenant",
        "datasets",
        ["tenant_id"],
        unique=True,
        sqlite_where=sa.text("status = 'ACTIVE'"),
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "handoff_tickets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("line_user_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_handoff_tickets_line_user_id"), "handoff_tickets", ["line_user_id"], unique=False
    )
    op.create_index(op.f("ix_handoff_tickets_status"), "handoff_tickets", ["status"], unique=False)
    op.create_index(
        op.f("ix_handoff_tickets_tenant_id"), "handoff_tickets", ["tenant_id"], unique=False
    )
    op.create_table(
        "line_channels",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("channel_secret_encrypted", sa.Text(), nullable=False),
        sa.Column("channel_access_token_encrypted", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", name="uq_line_channel_tenant"),
    )
    op.create_index(
        op.f("ix_line_channels_tenant_id"), "line_channels", ["tenant_id"], unique=False
    )
    op.create_table(
        "line_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("webhook_event_id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("line_user_id", sa.String(length=64), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "webhook_event_id", name="uq_line_event_id"),
    )
    op.create_index(
        op.f("ix_line_events_line_user_id"), "line_events", ["line_user_id"], unique=False
    )
    op.create_index(op.f("ix_line_events_status"), "line_events", ["status"], unique=False)
    op.create_index(op.f("ix_line_events_tenant_id"), "line_events", ["tenant_id"], unique=False)
    op.create_table(
        "outbox_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("line_user_id", sa.String(length=64), nullable=True),
        sa.Column("reply_token", sa.String(length=128), nullable=True),
        sa.Column("delivery_type", sa.String(length=16), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_outbox_messages_line_user_id"), "outbox_messages", ["line_user_id"], unique=False
    )
    op.create_index(op.f("ix_outbox_messages_status"), "outbox_messages", ["status"], unique=False)
    op.create_index(
        op.f("ix_outbox_messages_tenant_id"), "outbox_messages", ["tenant_id"], unique=False
    )
    op.create_table(
        "knowledge_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("dataset_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_knowledge_documents_dataset_id"),
        "knowledge_documents",
        ["dataset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_documents_tenant_id"), "knowledge_documents", ["tenant_id"], unique=False
    )
    op.create_table(
        "reservations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("service_id", sa.String(length=36), nullable=False),
        sa.Column("line_user_id", sa.String(length=64), nullable=False),
        sa.Column("customer_name", sa.String(length=160), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["service_id"], ["booking_services.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_reservation_idempotency"),
    )
    op.create_index(
        op.f("ix_reservations_line_user_id"), "reservations", ["line_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_reservations_service_id"), "reservations", ["service_id"], unique=False
    )
    op.create_index(op.f("ix_reservations_starts_at"), "reservations", ["starts_at"], unique=False)
    op.create_index(op.f("ix_reservations_status"), "reservations", ["status"], unique=False)
    op.create_index(op.f("ix_reservations_tenant_id"), "reservations", ["tenant_id"], unique=False)
    op.create_index(
        "uq_reservation_active_slot",
        "reservations",
        ["tenant_id", "starts_at"],
        unique=True,
        sqlite_where=sa.text("status IN ('HELD', 'CONFIRMED')"),
        postgresql_where=sa.text("status IN ('HELD', 'CONFIRMED')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_reservation_active_slot",
        table_name="reservations",
        sqlite_where=sa.text("status IN ('HELD', 'CONFIRMED')"),
        postgresql_where=sa.text("status IN ('HELD', 'CONFIRMED')"),
    )
    op.drop_index(op.f("ix_reservations_tenant_id"), table_name="reservations")
    op.drop_index(op.f("ix_reservations_status"), table_name="reservations")
    op.drop_index(op.f("ix_reservations_starts_at"), table_name="reservations")
    op.drop_index(op.f("ix_reservations_service_id"), table_name="reservations")
    op.drop_index(op.f("ix_reservations_line_user_id"), table_name="reservations")
    op.drop_table("reservations")
    op.drop_index(op.f("ix_knowledge_documents_tenant_id"), table_name="knowledge_documents")
    op.drop_index(op.f("ix_knowledge_documents_dataset_id"), table_name="knowledge_documents")
    op.drop_table("knowledge_documents")
    op.drop_index(op.f("ix_outbox_messages_tenant_id"), table_name="outbox_messages")
    op.drop_index(op.f("ix_outbox_messages_status"), table_name="outbox_messages")
    op.drop_index(op.f("ix_outbox_messages_line_user_id"), table_name="outbox_messages")
    op.drop_table("outbox_messages")
    op.drop_index(op.f("ix_line_events_tenant_id"), table_name="line_events")
    op.drop_index(op.f("ix_line_events_status"), table_name="line_events")
    op.drop_index(op.f("ix_line_events_line_user_id"), table_name="line_events")
    op.drop_table("line_events")
    op.drop_index(op.f("ix_line_channels_tenant_id"), table_name="line_channels")
    op.drop_table("line_channels")
    op.drop_index(op.f("ix_handoff_tickets_tenant_id"), table_name="handoff_tickets")
    op.drop_index(op.f("ix_handoff_tickets_status"), table_name="handoff_tickets")
    op.drop_index(op.f("ix_handoff_tickets_line_user_id"), table_name="handoff_tickets")
    op.drop_table("handoff_tickets")
    op.drop_index(
        "uq_dataset_active_per_tenant",
        table_name="datasets",
        sqlite_where=sa.text("status = 'ACTIVE'"),
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_index(op.f("ix_datasets_tenant_id"), table_name="datasets")
    op.drop_index(op.f("ix_datasets_status"), table_name="datasets")
    op.drop_table("datasets")
    op.drop_index(op.f("ix_conversation_messages_tenant_id"), table_name="conversation_messages")
    op.drop_index(op.f("ix_conversation_messages_line_user_id"), table_name="conversation_messages")
    op.drop_table("conversation_messages")
    op.drop_index(op.f("ix_business_hours_tenant_id"), table_name="business_hours")
    op.drop_table("business_hours")
    op.drop_index(op.f("ix_booking_services_tenant_id"), table_name="booking_services")
    op.drop_table("booking_services")
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_table("tenants")
    # ### end Alembic commands ###
