"""add rag chunks

Revision ID: bd881293bdf8
Revises: b44a5f565370
Create Date: 2026-07-23 10:40:51.400629
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "bd881293bdf8"
down_revision: str | None = "b44a5f565370"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_chunks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("dataset_id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("embedding_json", sa.Text(), nullable=False),
        sa.Column("embedding_model", sa.String(length=160), nullable=False),
        sa.Column("embedding_dimensions", sa.Integer(), nullable=False),
        sa.Column("token_count_estimate", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["knowledge_documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "position", name="uq_knowledge_chunk_position"),
    )
    op.create_index(
        op.f("ix_knowledge_chunks_content_hash"), "knowledge_chunks", ["content_hash"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_chunks_dataset_id"), "knowledge_chunks", ["dataset_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_chunks_document_id"), "knowledge_chunks", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_chunks_embedding_model"),
        "knowledge_chunks",
        ["embedding_model"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_chunks_tenant_id"), "knowledge_chunks", ["tenant_id"], unique=False
    )
    op.add_column(
        "knowledge_documents", sa.Column("content_hash", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "knowledge_documents",
        sa.Column("index_status", sa.String(length=24), server_default="PENDING", nullable=False),
    )
    op.add_column("knowledge_documents", sa.Column("index_error", sa.Text(), nullable=True))
    op.add_column(
        "knowledge_documents", sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        op.f("ix_knowledge_documents_index_status"),
        "knowledge_documents",
        ["index_status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_knowledge_documents_index_status"), table_name="knowledge_documents")
    op.drop_column("knowledge_documents", "indexed_at")
    op.drop_column("knowledge_documents", "index_error")
    op.drop_column("knowledge_documents", "index_status")
    op.drop_column("knowledge_documents", "content_hash")
    op.drop_index(op.f("ix_knowledge_chunks_tenant_id"), table_name="knowledge_chunks")
    op.drop_index(op.f("ix_knowledge_chunks_embedding_model"), table_name="knowledge_chunks")
    op.drop_index(op.f("ix_knowledge_chunks_document_id"), table_name="knowledge_chunks")
    op.drop_index(op.f("ix_knowledge_chunks_dataset_id"), table_name="knowledge_chunks")
    op.drop_index(op.f("ix_knowledge_chunks_content_hash"), table_name="knowledge_chunks")
    op.drop_table("knowledge_chunks")
    # ### end Alembic commands ###
