-- V7-V9 are reserved by the independent booking-service feature branch.
alter table line_events add column event_sequence bigint generated by default as identity;
create unique index uq_line_event_sequence on line_events(event_sequence);
create index ix_line_events_conversation_order
    on line_events(tenant_id, line_user_id, status, event_sequence);

create table conversation_turns (
    event_id varchar(36) primary key references line_events(id) on delete cascade,
    tenant_id varchar(36) not null references tenants(id) on delete cascade,
    line_user_id varchar(64) not null,
    source_key varchar(160) not null,
    customer_text text not null,
    reply_json text not null,
    state_json text not null,
    created_at timestamp with time zone not null,
    delivered_at timestamp with time zone
);
create index ix_conversation_turns_context
    on conversation_turns(tenant_id, line_user_id, source_key, created_at);
